name: SSH to Server

on: [push]

jobs:
  ssh-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 600 ssh_key

      - name: SSH into server and run commands
        run: |
          ssh -i ssh_key -o StrictHostKeyChecking=no ubuntu@ec2-13-213-18-81.ap-southeast-1.compute.amazonaws.com << 'EOF'
          mkdir phyomawko
          EOF
